# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170623_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='userpassword',
        ),
    ]
